[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sealed_bid_auction = "D1Zf4HpT6LpLZhGbUD4QXqAHjseNq2Ni8C4aVE2urtuw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
[[test.genesis]]
address = "F3G6Q9tRicyznCqcZLydJ6RxkwDSBeHWM458J7V6aeyk"
program = "/home/sal/Workspace/arcium/conviction/artifacts/arcium_program_0.5.4.so"
[[test.genesis]]
address = "L2TExMFKdjpN9kozasaurPirfHy9P8sbXoAN1qA3S95"
program = "artifacts/lighthouse.so"
