[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
opportunity_market = "opppkAuEoNg8W2bi6WGshmL8NWG2D4ATQWSgyhgTcSz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=b30e28f3-db3f-453d-9c9d-fb9ce0235a2e"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.test.ts\""

[test]
startup_wait = 9000000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899
