[localnet]
# default program keypair path
program_keypair = "../opppkAuEoNg8W2bi6WGshmL8NWG2D4ATQWSgyhgTcSz.json"
# number of nodes in the single cluster of the localnet
nodes = 2
# number of seconds to wait for the localnet to come online
localnet_timeout_secs = 60
# MPC backends this MXE supports (default: ["Cerberus"])
# Supported values: "Cerberus"
backends = ["Cerberus"]

[devnet]
# Cluster offset for devnet deployment
cluster_offset = 456
# MPC backends this MXE supports
backends = ["Cerberus"]
